# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Anders Blehr
author: Anders Blehr
email: anders@andersblehr.co
description: >- 
  Solving problems by distilling to their core.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username: andersblehr
twitter_username: andersblehr
linkedin_username: andersblehr
timezone: Europe/Oslo

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-redirect-from

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%-d %B %Y"
  home_is_blog: false
  show_footer_heading: false
  blog: # Optional settings for blog page
    title: Dalwhinnie past bedtime
    description: >-
      Here we are. Dalwhinnie past bedtime. Just need to get this working.

# Defaults for additional frontmatter settings
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      show_title: true
      suppress_list_title: false
  - scope:
      path: ""
      type: "posts"
    values:
      is_post: true


# Display post excerpts on the home page
show_excerpts: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
